### ISSUE TITLE
[Bug]: Error:stream error: stream ID 2557; INTERNAL_ERROR; received from peer

### ISSUE THREAD

**Issue by coreycusick** [FTBTeam/FTB-Server-Installer#2]
### Log Files

                                        Server installer version: v1.0.8(f1f067)
                                             Sun, 01 Dec 2024 06:34:33 UTC

                                                Installer Issue tracker
                                 https://github.com/FTBTeam/FTB-Server-Installer/issues
                                                            
 WARNING  Install directory is not empty, installing the modpack may cause issues
Would you like to continue? [y/N]: Yes
 INFO  Fetched modpack:
       Name: FTB Evolution
       Version: 1.3.0
       ModLoader: neoforge (21.1.74)
       Is Update: false
       Install Path: C:\Users\Corey\Desktop\FTB
Do you want to continue? [Y/n]: Yes
Do you want to download java? [Y/n]: No
 INFO  Starting mod pack download...
 WARNING  Failed to download:
          File: house1.png (https://files.feed-the-beast.com/blob/fc/fc0aab9447f37efadfc508394f3986ea62fc08263139a674c829b67dedae1b1e.png)
          Error:stream error: stream ID 2557; INTERNAL_ERROR; received from peer
  ERROR   Failed to download file: house1.png
          All mirrors failed

### Describe the issue

Unable to download FTB Evolution server files, attempted on multiple computers over multiple hours

### Steps to reproduce

Download FTB server files
Open them
Error appears

**Comment by Gaz492** [comment]
Hi,

Are you still running into this issue?
If you are would you be able to open the windows terminal/powershell where you have the installer downloaded then run the installer with the following command? You might need to change the name of the exe to match what you have
`powershell -Command { $env:GODEBUG="http2debug=2"; .\serverinstaller_125_12629 }`

This should show some more information about the error you are running into

**Comment by coreycusick** [comment]
My apologies. I forgot to close this. I was using a Proxmox VM, and my router was having an issue with that, fixed the router issue and the installer worked fine. I determined that to be the cause as when the installer was on my host machine, it worked perfectly fine

**Comment by CoLuxe** [comment]
> My apologies. I forgot to close this. I was using a Proxmox VM, and my router was having an issue with that, fixed the router issue and the installer worked fine. I determined that to be the cause as when the installer was on my host machine, it worked perfectly fine

What was your issue? Im having the same problem running it on Proxmox in a Debian VM with an OPNSense Router.

**Comment by coreycusick** [comment]
I had to disable my second router in bridged mode, it caused the problem
