### ISSUE TITLE
[Bug]: Installer Fails to Start on Windows Server 2008

### ISSUE THREAD

**Issue by r-mc2** [FTBTeam/FTB-Server-Installer#3]
### Log Files

N/A

### Describe the issue

I have a dedicated server running an older version of Windows Server and the executable will not even start when trying to set up Evolution v1.4.1

I'm not sure if it's a limitation of older versions of Windows or what.

![image](https://github.com/user-attachments/assets/a5de64fc-d242-4f10-ae52-2fc4ca59efc4)

---

At the moment my workaround has been to open a SMB share to my server and run this program on my local machine, having the installer try to download and copy over the network back up to the dedi.

However, it did fail when trying to run the neoforge installer.
```log
JVM info: Eclipse Adoptium - 21.0.5 - 21.0.5+11-LTS

Exception in thread "main" java.lang.IllegalArgumentException: URI has an authority component
	at java.io.File.<init>(Unknown Source)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:77)
```
This is with Microsoft's OpenJDK v21.0.5

### Steps to reproduce

1. Download installer
2. Run installer on Windows Server 2008

**Comment by Gaz492** [comment]
After having looked into this, the installer is incompatible with Windows server 2008/2008r2 or Windows server 2012 due golang having dropped support for those versions.

As for the java error you are also getting, im not sure what would be causing that to happen, it may be the SMB share thats causing this specific issue. I would suggest trying to install the server fully on your local machine (not in the smb share) then move the files over to your server and see if it runs. It may be the case that neoforge/java 21 also doesn't work properly on windows server 2008.

**Comment by r-mc2** [comment]
Ahh, thanks for digging into this, Gaz.

I was thinking it was something like that for the neoforge installer. I'm assuming it didn't like the cross-network downloading.

And for getting it going, that's actually exactly what I ended up doing. Used the installer locally, zipped up the directory, and moved that over to the dedi. Server does run fine once it's all unpacked in the new location.
Was hoping there was an easier way as I'm not sure how easy it'll be to do the upgrade runs of the installer over the SMB connection. But understandable the O/S is too old.
